'use strict';
const KEY='fudibox-demo-v1';
const catalog=[{id:1,name:'Pollo rostizado familiar',description:'Una pieza · presentación fija',price:15000,icon:'🍗'},{id:2,name:'Papas de la casa',description:'Porción de 300 g',price:4500,icon:'🥔'},{id:3,name:'Agua de jamaica',description:'Botella de 1 litro',price:3000,icon:'🥤'}];
let state={orders:[],principal:'',respaldo:''};
try{const saved=JSON.parse(localStorage.getItem(KEY));if(saved&&Array.isArray(saved.orders))state={...state,...saved};}catch{}
let role='cliente';
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cash=v=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(v/100);
const labels={requested:'Por confirmar',quote:'Esperando cotización',quoted:'Cotización lista',preparing:'En preparación',ready:'Listo para recoger',delivered:'Entregado',expired:'Cotización vencida'};
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch{throw Error('No se pudo guardar. Habilita almacenamiento del navegador antes de continuar.');}}
function inform(message){$('#notice').textContent=message;}
function expire(){let changed=false;state.orders.forEach(o=>{if(o.status==='quoted'&&Date.now()>=o.expires){o.status='expired';changed=true;}});if(changed)save();return changed;}
function total(o){return o.subtotal+1000+(o.shipping??0);}
function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);}
function code(){const a=new Uint32Array(1);crypto.getRandomValues(a);return String(100000+a[0]%900000);}
function message(o){return [`FudiBOX · ${o.number}`,`RECOGER: Chicken Chicanito (negocio de demostración)`,`Ubicación de recogida: pendiente de configurar`,`ENTREGAR: ${o.address}`,`Cliente: ${o.name} · ${o.phone}`,`Preparación estimada: ${o.minutes||'Por confirmar'} min después de aceptar`,...o.items.map(i=>`${i.qty} × ${i.name}`),`ADELANTAR AL NEGOCIO: ${cash(o.subtotal+1000)}`,o.shipping===null?'ENVÍO: por cotizar':`PAGO DEL REPARTO: ${cash(o.shipping)}`,o.shipping===null?'TOTAL CLIENTE: pendiente de cotización':`COBRAR AL CLIENTE: ${cash(total(o))}`,`Responsable: ${o.owner==='principal'?'Principal':'Respaldo'}`,`Estado: ${labels[o.status]}`].join('\n');}
function whatsapp(o,customer=false){const phone=(customer?o.phone:state[o.owner]).replace(/\D/g,'');if(phone.length<10||phone.length>15)throw Error(customer?'Registra un teléfono con código de país válido.':'Configura el número del coordinador en Administración, con código de país.');const text=customer?`FudiBOX · ${o.number}\nTu envío cuesta ${cash(o.shipping)}. Total: ${cash(total(o))}. La cotización vence a las ${new Date(o.expires).toLocaleTimeString('es-MX')}.\nDEMO LOCAL: todavía no hay enlace público de aceptación. No enviar como pedido real.`:message(o);window.open('https://wa.me/'+phone+'?text='+encodeURIComponent(text),'_blank','noopener,noreferrer');inform('Se abrió un mensaje preparado. Debes pulsar Enviar en WhatsApp. FudiBOX no confirma su recepción.');}
function orderCard(o){const sum=`<div class="row"><span>Productos + FudiBOX</span><strong>${cash(o.subtotal+1000)}</strong></div><div class="row"><span>Envío</span><strong>${o.delivery==='pickup'?'No aplica':o.shipping===null?'Por cotizar':cash(o.shipping)}</strong></div><div class="row summary"><strong>${o.shipping===null?'Subtotal sin envío':'Total'}</strong><span class="money">${cash(total(o))}</span></div>`;
let controls='';const ended=['delivered','expired'].includes(o.status);
if(role==='cliente'){
if(o.status==='quoted')controls+=`<p>Cotización válida hasta ${new Date(o.expires).toLocaleTimeString('es-MX')}. <strong data-countdown="${o.expires}"></strong></p><button data-action="accept" data-id="${o.id}">Aceptar total de ${cash(total(o))}</button>`;
if(['preparing','ready'].includes(o.status))controls+=`<p>Tu código de entrega. Compártelo al recibir:</p><div class="code">${o.code}</div>`;
}
if(role==='negocio'){
if(o.status==='requested')controls+=`<label>Minutos de preparación<input id="minutes-${o.id}" type="number" min="1" max="240" value="20"></label><button data-action="confirm" data-id="${o.id}">Confirmar disponibilidad</button>`;
if(o.delivery==='delivery'&&!ended&&o.status!=='requested')controls+=`<div class="actions"><button data-action="whatsapp" data-id="${o.id}">Solicitar repartidor por WhatsApp</button>${o.owner==='principal'?`<button class="warn" data-action="backup" data-id="${o.id}">Solicitar apoyo</button>`:''}</div>`;
if(o.status==='preparing')controls+=`<div class="actions"><button data-action="ready" data-id="${o.id}">Marcar listo para recoger</button></div>`;
if(o.delivery==='pickup'&&o.status==='ready')controls+=finishControl(o);
}
if(role==='coordinador'&&o.delivery==='delivery'){
if(o.status==='quote')controls+=`<label>Precio del envío en MXN<input id="shipping-${o.id}" type="number" min="0" step="0.01" placeholder="30.00"></label><button data-action="quote" data-id="${o.id}">Publicar cotización · 10 minutos</button>`;
if(o.status==='quoted')controls+=`<button data-action="notify" data-id="${o.id}">Avisar al cliente por WhatsApp</button>`;
if(['preparing','ready'].includes(o.status)&&!o.driver)controls+=`<label>Nombre del repartidor<input id="driver-${o.id}" maxlength="80" placeholder="Repartidor asignado en el grupo"></label><button data-action="assign" data-id="${o.id}">Registrar asignación</button>`;
if(o.status==='ready'&&o.driver)controls+=finishControl(o);
}
return `<article class="card"><div class="row"><strong>${o.number}</strong><span class="badge">${labels[o.status]}</span></div><h3>${esc(o.name)} · ${o.delivery==='pickup'?'Recoger':'A domicilio'}</h3><p class="muted">${o.delivery==='delivery'?esc(o.address):'Recoger en Chicken Chicanito'}<br>${o.delivery==='delivery'?'Coordinador: '+esc(o.owner)+(o.driver?' · Repartidor: '+esc(o.driver):''):''}</p>${sum}<div class="actions">${controls}</div>${o.status==='expired'?'<p>Solicitud cancelada por vencimiento. No preparar ni asignar.</p>':''}</article>`;
}
function finishControl(o){return `<label>Código que entrega el cliente<input id="code-${o.id}" inputmode="numeric" maxlength="6" autocomplete="off" placeholder="6 dígitos"></label><button data-action="finish" data-id="${o.id}">Validar y completar entrega</button>`;}
function render(){expire();document.querySelectorAll('[data-role]').forEach(b=>b.classList.toggle('active',b.dataset.role===role));const titles={cliente:['Lo bueno está cerca.','Pide a tu negocio local. El envío se cotiza antes de preparar.'],negocio:['Tu cocina, en orden.','Confirma disponibilidad. Prepara cuando el cliente acepte el total.'],coordinador:['Cada entrega, acompañada.','Cotiza, coordina en tu grupo y confirma la entrega.'],admin:['El pulso de FudiBOX.','Configuración y adeudos de demostración.']};$('#intro').innerHTML=`<span class="eyebrow">FudiBOX / ${role}</span><h1>${titles[role][0]}</h1><p>${titles[role][1]}</p>`;
if(role==='cliente')$('#intro').innerHTML=`<div class="location-line"><span>⌖ Jojutla y alrededores</span><span>Tu comunidad. Tus negocios.</span></div><section class="fudi-hero"><div class="hero-copy"><span class="hero-kicker">¡QUÉ ONDA! SOY FUDI, TU REPA.</span><h1>Tú pon el antojo.<br>Yo me pongo <em>al tiro.</em></h1><p>Puro sabor de por acá, hasta tu puerta.<br>Checa los negocios y arma algo rico.</p><a class="hero-cta" href="#merchant">Órale, ¿qué se te antoja? <span aria-hidden="true">↗</span></a><div class="hero-notes"><span>Negocios locales</span><span>Pago al recibir</span></div></div><div class="mascot-scene"><div class="orbit"></div><span class="route-label">DE TU BARRIO<br><strong>A TU PUERTA</strong></span><img src="assets/fudi-repa-v2-uniforme.png" alt="Fudi, el robot repartidor de casco naranja y mochila de entregas, te saluda"></div></section><div class="discovery-title"><div><span class="eyebrow">SABOR DE POR ACÁ</span><h2>Acá se come machín.</h2></div><span class="local-pill">Hecho en Jojutla</span></div>`;
if(role==='cliente')$('#app').innerHTML=`<div class="grid"><section><article class="merchant-card" id="merchant"><div class="merchant-cover"><div><span class="merchant-tag">PRIMER NEGOCIO EN FUDIBOX</span><h2>El antojo tiene<br>nombre propio.</h2></div><img src="assets/chicanito-pollo.png" alt="Pollo rostizado Chicken Chicanito"></div><div class="merchant-details"><img class="merchant-logo" src="assets/chicanito-logo.jpg" alt="Logo Chicken Chicanito"><div><h2>Chicken Chicanito</h2><p>Pollo y comida preparada · Jojutla</p></div></div><div class="merchant-bottom"><span>A domicilio o para recoger</span><span>Menú de ejemplo</span></div></article><form id="order-form" class="card">${catalog.map(p=>`<div class="product"><span class="emoji" aria-hidden="true">${p.icon}</span><div class="info"><strong>${p.name}</strong><p>${p.description}</p><strong>${cash(p.price)}</strong></div><input aria-label="Cantidad de ${p.name}" type="number" id="qty-${p.id}" min="0" max="20" value="${p.id===1?1:0}"></div>`).join('')}<label>Tu nombre<input name="name" required maxlength="80" placeholder="Nombre de demostración"></label><label>Teléfono con código de país<input name="phone" required pattern="[+0-9 ()-]{10,20}" placeholder="+52…"></label><label>Entrega<select name="delivery"><option value="delivery">A domicilio · envío por cotizar</option><option value="pickup">Recoger en el negocio</option></select></label><label>Dirección o enlace de ubicación y referencias<textarea name="address" maxlength="500" placeholder="Usa datos ficticios para probar"></textarea></label><p class="muted">Se suman $10 de servicio FudiBOX. Para domicilio aceptarás el total cuando esté cotizado. Todo se paga al recibir o recoger.</p><button type="submit">Solicitar pedido</button></form></section><section><div class="orders-heading"><span class="eyebrow">AL TIRO CON TU PEDIDO</span><h2>Tu pedido, por aquí.</h2></div>${state.orders.slice().reverse().map(orderCard).join('')||'<div class="empty"><div class="empty-symbol" aria-hidden="true">＋</div><h3>Sí, pues… ¿qué vas a pedir?</h3><p>Arma algo rico de Chicken Chicanito.<br>Aquí verás la cotización y el avance de tu pedido.</p><span class="badge">Tu envío se confirma antes de preparar</span></div><div class="community-card"><span class="eyebrow">ESTO SE VA A PONER DE POCA…</span><h3>Más barrio.<br>Más para elegir.</h3><p>Le estamos echando ganas para sumar más negocios de por acá.</p></div>'}</section></div>`;
else if(role==='admin'){const completed=state.orders.filter(o=>o.status==='delivered');$('#app').innerHTML=`<div class="grid"><section class="card"><span class="eyebrow">COCINA DEL CENTRO</span><h2>Adeudo acumulado</h2><span class="money">${cash(completed.length*1000)}</span><p>${completed.length} pedidos completados × $10. Sin liquidaciones registradas en esta demo.</p><p class="muted">El corte semanal y registro de pagos se implementarán en el backend.</p></section><form id="settings" class="card"><h2>Coordinadores</h2><p class="muted">Solo se abre WhatsApp al pulsar su botón. Usa números propios para pruebas.</p><label>Principal · código de país y número<input name="principal" value="${esc(state.principal)}" placeholder="52…"></label><label>Respaldo · código de país y número<input name="respaldo" value="${esc(state.respaldo)}" placeholder="52…"></label><button>Guardar números localmente</button></form></div>`;}
else {const list=state.orders.filter(o=>role!=='coordinador'||o.delivery==='delivery');$('#app').innerHTML=(role==='coordinador'?'<p class="steps">Vista de demostración de ambos responsables. En producción cada coordinador verá solamente sus pedidos autorizados.</p>':'')+`<div class="grid">${list.slice().reverse().map(orderCard).join('')||'<div class="empty">Aún no hay pedidos. Crea uno desde Cliente.</div>'}</div>`;}countdown();}
function countdown(){document.querySelectorAll('[data-countdown]').forEach(el=>{const s=Math.max(0,Math.ceil((Number(el.dataset.countdown)-Date.now())/1000));el.textContent=`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')} restantes`;});}
document.addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;try{if(b.dataset.role){role=b.dataset.role;inform('');render();return;}const action=b.dataset.action;if(!action)return;if(expire()){render();throw Error('La cotización venció. El estado del pedido se actualizó.');}const o=state.orders.find(o=>o.id===b.dataset.id);if(!o)return;
if(action==='confirm'&&o.status==='requested'){const mins=Number($('#minutes-'+o.id).value);if(!Number.isInteger(mins)||mins<1||mins>240)throw Error('Indica entre 1 y 240 minutos.');o.minutes=mins;o.status=o.delivery==='pickup'?'preparing':'quote';}
else if(action==='quote'&&o.status==='quote'){const raw=$('#shipping-'+o.id).value;const n=Number(raw);if(!raw||!Number.isFinite(n)||n<0||n>10000)throw Error('Indica un precio válido de envío.');o.shipping=Math.round(n*100);o.expires=Date.now()+600000;o.status='quoted';}
else if(action==='accept'&&o.status==='quoted'){o.status='preparing';o.acceptedAt=Date.now();}
else if(action==='ready'&&o.status==='preparing'){o.status='ready';}
else if(action==='assign'&&['preparing','ready'].includes(o.status)){const name=$('#driver-'+o.id).value.trim();if(!name)throw Error('Escribe el nombre del repartidor.');if(state.orders.some(x=>x.id!==o.id&&!['delivered','expired'].includes(x.status)&&x.driver?.toLowerCase()===name.toLowerCase()))throw Error('Ese repartidor ya tiene un pedido activo.');o.driver=name;}
else if(action==='finish'&&o.status==='ready'){if((o.attempts||0)>=5)throw Error('Cinco intentos fallidos. Requiere intervención; la recuperación administrativa está pendiente.');if($('#code-'+o.id).value.trim()!==o.code){o.attempts=(o.attempts||0)+1;save();throw Error('Código incorrecto. Confírmalo con el cliente.');}o.status='delivered';o.completedAt=Date.now();}
else if(action==='backup'&&o.owner==='principal'){o.owner='respaldo';save();render();whatsapp(o);return;}
else if(action==='whatsapp'){whatsapp(o);return;}
else if(action==='notify'){whatsapp(o,true);return;}
else throw Error('Esta acción ya no corresponde al estado actual del pedido.');save();inform('Actualizado y guardado en este navegador.');render();}catch(error){inform(error.message);}});
document.addEventListener('submit',event=>{event.preventDefault();try{const form=event.target;const data=new FormData(form);if(form.id==='settings'){state.principal=String(data.get('principal')).trim();state.respaldo=String(data.get('respaldo')).trim();save();inform('Números guardados localmente.');return;}if(form.id!=='order-form')return;const items=catalog.map(p=>({...p,qty:Number($('#qty-'+p.id).value)})).filter(p=>p.qty>0);if(!items.length||items.some(i=>!Number.isInteger(i.qty)||i.qty>20))throw Error('Elige al menos un producto; máximo 20 unidades por producto.');const delivery=data.get('delivery');const address=String(data.get('address')).trim();if(delivery==='delivery'&&!address)throw Error('Indica dirección o ubicación y referencias.');const name=String(data.get('name')).trim();if(!name)throw Error('Escribe tu nombre.');state.orders.push({id:uid(),number:'FUDI-'+String(state.orders.length+1).padStart(4,'0'),name,phone:String(data.get('phone')).trim(),address,delivery,items,subtotal:items.reduce((sum,p)=>sum+p.price*p.qty,0),shipping:delivery==='pickup'?0:null,status:'requested',owner:'principal',code:code(),createdAt:Date.now()});save();inform('¡Va que va! Solicitud guardada. Cambia a Negocio para confirmar disponibilidad.');render();}catch(error){inform(error.message);}});
setInterval(()=>{try{if(expire())render();else countdown();}catch(error){inform(error.message);}},1000);
window.addEventListener('storage',event=>{if(event.key===KEY&&event.newValue){try{state=JSON.parse(event.newValue);render();}catch{inform('No se pudo sincronizar la demostración local.');}}});
render();
