begin;
create temporary table fudibox_test_results(test text,passed boolean);
do $$
declare uid uuid; stranger uuid:=gen_random_uuid(); bid uuid; pid uuid; oid uuid; retry uuid; payload jsonb; key uuid:=gen_random_uuid(); n integer; rejected boolean;
begin
 select id into strict uid from auth.users where lower(email)='miguel.e.portilla@gmail.com' and email_confirmed_at is not null;
 insert into public.businesses(name,slug,status,address,latitude,longitude,accepting_orders)
 values('TEST rollback','test-'||gen_random_uuid(),'approved','Dirección ficticia solo prueba',18,-99,false) returning id into bid;
 insert into public.products(business_id,name,price_cents,available,track_stock,stock_units,option_groups)
 values(bid,'TEST producto',1000,true,true,3,'[{"name":"Adobo","choices":["BBQ"]}]') returning id into pid;
 insert into fudi_private.business_members(business_id,user_id,role,active) values(bid,uid,'owner',true);
 payload:=jsonb_build_object('business_id',bid,'name','TEST','phone','+527340000000','delivery_method','pickup','address','','notes','','expected_subtotal',2000,'items',jsonb_build_array(jsonb_build_object('product_id',pid,'quantity',2,'choices',jsonb_build_object('Adobo','BBQ'))));
 perform set_config('request.jwt.claim.sub','',true);
 rejected:=false; begin perform public.create_customer_order(key,payload); exception when invalid_authorization_specification then rejected:=true; end;
 if not rejected then raise exception 'FAILED anonymous order'; end if;
 insert into fudibox_test_results values('anonymous order rejected',true);
 perform set_config('request.jwt.claim.sub',uid::text,true);
 rejected:=false; begin perform public.create_customer_order(key,payload); exception when raise_exception then rejected:=true; end;
 if not rejected then raise exception 'FAILED closed business'; end if;
 insert into fudibox_test_results values('closed business rejected',true);
 update public.businesses set accepting_orders=true where id=bid;
 rejected:=false; begin perform public.create_customer_order(gen_random_uuid(),jsonb_set(payload,'{expected_subtotal}','1')); exception when raise_exception then rejected:=true; end;
 if not rejected then raise exception 'FAILED price tampering'; end if;
 insert into fudibox_test_results values('price tampering rejected',true);
 rejected:=false; begin perform public.create_customer_order(gen_random_uuid(),jsonb_set(payload,'{items,0,choices}','{}')); exception when raise_exception then rejected:=true; end;
 if not rejected then raise exception 'FAILED missing options'; end if;
 insert into fudibox_test_results values('missing options rejected',true);
 oid:=public.create_customer_order(key,payload);
 select stock_units into n from public.products where id=pid;
 if n<>1 then raise exception 'FAILED reservation'; end if;
 retry:=public.create_customer_order(key,payload);
 select stock_units into n from public.products where id=pid;
 if retry<>oid or n<>1 then raise exception 'FAILED idempotence'; end if;
 insert into fudibox_test_results values('atomic reservation and idempotent retry',true);
 rejected:=false; begin perform public.create_customer_order(key,jsonb_set(payload,'{notes}','"changed"')); exception when raise_exception then rejected:=true; end;
 if not rejected then raise exception 'FAILED reused key mismatch'; end if;
 insert into fudibox_test_results values('mismatched retry rejected',true);
 rejected:=false; begin perform public.create_customer_order(gen_random_uuid(),payload); exception when raise_exception then rejected:=true; end;
 if not rejected then raise exception 'FAILED stock oversell'; end if;
 insert into fudibox_test_results values('insufficient stock rejected',true);
 perform set_config('request.jwt.claim.sub',stranger::text,true);
 rejected:=false; begin perform public.confirm_business_order(oid,20); exception when insufficient_privilege then rejected:=true; end;
 if not rejected then raise exception 'FAILED foreign confirmation'; end if;
 rejected:=false; begin perform public.cancel_pending_order(oid); exception when insufficient_privilege then rejected:=true; end;
 if not rejected then raise exception 'FAILED foreign cancellation'; end if;
 rejected:=false; begin perform public.set_product_availability(pid,false); exception when insufficient_privilege then rejected:=true; end;
 if not rejected then raise exception 'FAILED foreign catalog mutation'; end if;
 insert into fudibox_test_results values('foreign user mutations rejected',true);
 perform set_config('request.jwt.claim.sub',uid::text,true);
 perform public.cancel_pending_order(oid);
 perform public.cancel_pending_order(oid);
 select stock_units into n from public.products where id=pid;
 if n<>3 then raise exception 'FAILED cancel release'; end if;
 insert into fudibox_test_results values('cancellation releases stock exactly once',true);
 oid:=public.create_customer_order(gen_random_uuid(),payload);
 perform public.confirm_business_order(oid,20);
 perform public.confirm_business_order(oid,20);
 if (select status from public.orders where id=oid)<>'preparing' then raise exception 'FAILED pickup preparation'; end if;
 insert into fudibox_test_results values('pickup confirmation idempotent',true);
 rejected:=false; begin perform public.cancel_pending_order(oid); exception when raise_exception then rejected:=true; end;
 if not rejected then raise exception 'FAILED late cancel'; end if;
 insert into fudibox_test_results values('cancellation after preparation rejected',true);
 perform set_config('request.jwt.claim.sub',stranger::text,true);
end $$;
grant select on fudibox_test_results to authenticated;
set local role authenticated;
do $$ begin
 if (select count(*) from public.orders)<>0 then raise exception 'FAILED foreign RLS'; end if;
 if (select count(*) from public.my_businesses())<>0 then raise exception 'FAILED membership isolation'; end if;
 if has_table_privilege('authenticated','public.orders','INSERT') then raise exception 'FAILED direct insert grants'; end if;
end $$;
reset role;
insert into fudibox_test_results values('RLS isolation and direct write denial',true);
select * from fudibox_test_results;
rollback;