import Link from "next/link";
import { requireOperator } from "@/lib/operator";
import { money,orderLabels } from "@/lib/catalog";
import { saveBusiness,saveDriver,saveProduct,confirmOrder,cancelOrder,markPickupReady,completePickup } from "./actions";
import { signOut } from "@/app/cuenta/actions";
export const dynamic="force-dynamic";
type B={id:string;name:string;slug:string;address:string|null;status:string;accepting_orders:boolean};
type D={id:string;display_name:string;phone:string;business_id:string|null;shared:boolean;approved:boolean};
type P={id:string;business_id:string;name:string;description:string;category:string;price_cents:number;available:boolean};
export default async function Operator({searchParams}:{searchParams:Promise<{section?:string;business?:string;error?:string;saved?:string}>}){
 const client=await requireOperator();const q=await searchParams;
 const section=["pedidos","restaurantes","menu","repas"].includes(q.section||"")?q.section!:"pedidos";
 const {data:businesses,error:bError}=await client.from("businesses").select("id,name,slug,address,status,accepting_orders").order("name");
 if(bError)throw new Error("No se pudieron consultar restaurantes.");
 const list=(businesses||[]) as B[];
 const selected=list.find(b=>b.id===q.business)||list[0];
 const businessOptions=<><option value="">Selecciona restaurante</option>{list.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</>;
 function businessForm(b?:B){return <form action={saveBusiness} className="operator-form"><input type="hidden" name="id" value={b?.id||""}/><label>Nombre<input name="name" defaultValue={b?.name} required maxLength={160}/></label><label>Identificador para el enlace<input name="slug" defaultValue={b?.slug} required pattern="[a-z0-9]+(-[a-z0-9]+)*" maxLength={100} placeholder="nombre-del-restaurante"/></label><label>Dirección<textarea name="address" defaultValue={b?.address||""} maxLength={500}/></label><label className="check"><input type="checkbox" name="approved" defaultChecked={b?.status==="approved"}/>Mostrar en la tienda</label><p className="fine">Guardar mantiene la recepción cerrada durante esta etapa. Publicar el menú no habilita pedidos.</p><button className="button">Guardar restaurante</button></form>;}
 function driverForm(d?:D){return <form action={saveDriver} className="operator-form"><input name="id" type="hidden" value={d?.id||""}/><label>Nombre<input name="name" defaultValue={d?.display_name} required maxLength={120}/></label><label>Teléfono de México<input name="phone" type="tel" inputMode="numeric" pattern="[0-9]{10}" maxLength={10} defaultValue={d?.phone.replace(/^\+52/,"")} required/></label><label>Restaurante<select name="business_id" defaultValue={d?.business_id||""}>{businessOptions}</select></label><label className="check"><input type="checkbox" name="shared" defaultChecked={d?.shared}/>Repa compartido</label><label className="check"><input type="checkbox" name="approved" defaultChecked={d?.approved}/>Contacto aprobado</label><button className="button">Guardar repa</button></form>;}
 function productForm(p?:P){return <form action={saveProduct} className="operator-form"><input type="hidden" name="id" value={p?.id||""}/><input type="hidden" name="business_id" value={selected?.id||""}/><label>Nombre<input name="name" defaultValue={p?.name} required maxLength={160}/></label><label>Descripción<textarea name="description" defaultValue={p?.description} maxLength={2000}/></label><label>Precio en pesos<input type="number" name="price" min="0" max="9999999" step=".01" defaultValue={p?(p.price_cents/100).toFixed(2):""} required/></label><label>Categoría<input name="category" defaultValue={p?.category||"Menú"} required maxLength={100}/></label><label className="check"><input type="checkbox" name="available" defaultChecked={p?.available}/>Disponible</label><p className="fine">{p?"Se conservan las fotos y opciones actuales.":"Alta de producto sencillo, sin opciones ni foto. Los paquetes personalizables requieren configuración adicional."}</p><button className="button">Guardar producto</button></form>;}
 let content;
 if(section==="restaurantes")content=<><details className="card"><summary>Agregar restaurante</summary>{businessForm()}</details>{list.map(b=><details className="card" key={b.id}><summary>{b.name} · {b.status==="approved"?"Visible":"Borrador"}</summary><p><Link href={"/restaurantes/"+b.slug}>Ver menú ↗</Link></p>{businessForm(b)}</details>)}</>;
 else if(section==="repas"){
 const {data,error}=await client.from("drivers").select("id,display_name,phone,business_id,shared,approved").order("display_name");if(error)throw new Error("No se pudieron consultar repas.");
 content=<><p>Contactos para coordinar por WhatsApp. No son cuentas de acceso. La asignación a pedidos aún está pendiente.</p><details className="card"><summary>Agregar repa</summary>{driverForm()}</details>{(data as D[]||[]).map(d=><details className="card" key={d.id}><summary>{d.display_name} · {d.approved?"Aprobado":"Pendiente"}</summary><p>{d.phone}</p><a className="text-link" target="_blank" rel="noreferrer" href={"https://wa.me/"+d.phone.replace(/\D/g,"")}>Abrir conversación en WhatsApp ↗</a>{driverForm(d)}</details>)}</>;
 }else if(section==="menu"){
 const {data,error}=selected?await client.from("products").select("id,business_id,name,description,category,price_cents,available").eq("business_id",selected.id).order("sort_order"):{data:[],error:null};if(error)throw new Error("No se pudo consultar el menú.");
 content=<><form className="operator-form" method="get"><input type="hidden" name="section" value="menu"/><label>Restaurante<select name="business" defaultValue={selected?.id}>{businessOptions}</select></label><button className="button">Ver menú</button></form>{selected?<><h2>{selected.name}</h2><details className="card"><summary>Agregar producto sencillo</summary>{productForm()}</details>{(data as P[]||[]).map(p=><details className="card" key={p.id}><summary>{p.name} · {money(p.price_cents)} · {p.available?"Disponible":"Agotado"}</summary>{productForm(p)}</details>)}</>:<p>Agrega primero un restaurante.</p>}</>;
 }else{
 const {data,error}=await client.from("orders").select("id,business_id,status,customer_name,customer_phone,delivery_method,delivery_address,notes,subtotal_cents,total_cents,created_at,completed_at,order_items(product_name,quantity,selections)").order("created_at",{ascending:false}).limit(100);
 if(error)throw new Error("No se pudieron consultar pedidos.");
 content=<><p>Últimos 100 pedidos. Recarga para consultar cambios. Tú confirmas con el restaurante antes de actualizar el pedido.</p>{!data?.length?<div className="card"><h2>Sin pedidos recibidos</h2><p>La recepción sigue cerrada mientras terminamos entrega y cierre.</p></div>:data.map(o=><article className="card" key={o.id}><span className="badge">{orderLabels[o.status]||o.status}</span><h2>{list.find(b=>b.id===o.business_id)?.name}</h2><p>{o.customer_name} · {o.customer_phone}</p><p>{o.delivery_method==="pickup"?"Recoger en restaurante":"A domicilio"} {o.delivery_address}</p><ul>{o.order_items.map((i:{product_name:string;quantity:number;selections:{quantity:number;choices:Record<string,string>}[]},n:number)=><li key={n}>{i.quantity} × {i.product_name}<p className="fine">{i.selections?.map(s=>s.quantity+" × "+Object.entries(s.choices).map(([k,v])=>k+": "+v).join(", ")).join(" / ")}</p></li>)}</ul><p>{o.notes}</p><strong>{o.total_cents===null?money(o.subtotal_cents+1000)+" + envío por cotizar":money(Number(o.total_cents))}</strong>{o.status==="requested"&&<form action={confirmOrder} className="operator-form"><input type="hidden" name="order_id" value={o.id}/><label>Tiempo confirmado con restaurante (minutos)<input name="minutes" type="number" min="1" max="240" required defaultValue="20"/></label><button className="button">Confirmar disponibilidad</button></form>}{o.status==="preparing"&&o.delivery_method==="pickup"&&<form action={markPickupReady}><input type="hidden" name="order_id" value={o.id}/><p>Confirma con el restaurante que el pedido está preparado antes de marcarlo listo.</p><button className="button">Marcar listo para recoger</button></form>}{o.status==="ready"&&o.delivery_method==="pickup"&&<form action={completePickup} className="operator-form"><input type="hidden" name="order_id" value={o.id}/><label className="check"><input type="checkbox" name="received" required/>Confirmé con el restaurante que el cliente recibió su pedido.</label><p className="fine">Se registrará el cargo de servicio de $10 una sola vez. Esto no registra una liquidación del restaurante.</p><button className="button">Confirmar recogida y cerrar pedido</button></form>}{o.status==="delivered"&&<p>Recogida confirmada · {o.completed_at&&new Date(o.completed_at).toLocaleString("es-MX",{timeZone:"America/Mexico_City"})}</p>}{o.status==="awaiting_quote"&&<p>Esperando cotización. No iniciar preparación. Esta etapa aún está pendiente de implementación.</p>}{["requested","awaiting_quote","quoted"].includes(o.status)&&<form action={cancelOrder}><input name="order_id" type="hidden" value={o.id}/><button className="button secondary">Cancelar y liberar reserva</button></form>}</article>)}</>;
 }
 return <><nav className="operator-nav" aria-label="Operación">{[["pedidos","Pedidos"],["restaurantes","Restaurantes"],["menu","Menús"],["repas","Repas"]].map(([key,label])=><Link key={key} href={"/admin?section="+key} aria-current={section===key?"page":undefined}>{label}</Link>)}<form action={signOut}><button>Cerrar sesión</button></form></nav><div className="menu-notice">Operación centralizada · Recepción de pedidos aún cerrada. Los restaurantes y repas no necesitan una app.</div>{q.error&&<p className="alert" role="alert">No se guardó el cambio. Revisa los campos, posibles duplicados y tu acceso.</p>}{q.saved&&<p role="status" className="badge">Cambios guardados</p>}<div className="operator-content">{content}</div></>;
}